# Generated by Django 5.2.5 on 2025-09-09 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "permissions": [
                    ("view_user_list", "Может просматривать список пользователей"),
                    ("block_users", "Может блокировать/разблокировать пользователей"),
                ]
            },
        ),
    ]
