# Generated by Django 5.2.5 on 2025-09-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_client_options_attempt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-id'], 'permissions': [('view_all_clients', 'Может просматривать всех клиентов')], 'verbose_name': 'получатель', 'verbose_name_plural': 'получатели'},
        ),
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('view_all_mailings', 'Может просматривать все рассылки'), ('disable_mailings', 'Может отключать рассылки пользователей')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'permissions': [('view_all_messages', 'Может просматривать все сообщения')], 'verbose_name': 'сообщение', 'verbose_name_plural': 'сообщения'},
        ),
        migrations.AddField(
            model_name='mailing',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='Включена'),
        ),
    ]
